# Generated by Django 2.1.1 on 2018-09-09 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocTechnicalReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagEtudeNum', models.CharField(max_length=100)),
                ('tagDocNameShort', models.CharField(max_length=100)),
                ('tagDocName', models.CharField(max_length=100)),
                ('tagDocDate', models.CharField(max_length=100)),
                ('tagClientCompagny', models.CharField(max_length=100)),
                ('tagCommercialNom', models.CharField(max_length=100)),
                ('tagCommercialPrenom', models.CharField(max_length=100)),
                ('tagDocVersion', models.CharField(max_length=100)),
            ],
        ),
    ]
